name: Build and deploy
on: [push, pull_request]
jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        dotnet: ['3.1.200', '5.0.x']
        include:
          - dotnet: '3.1.200'
            framework: netcoreapp3.0
          - dotnet: '5.0.x'
            framework: net5
      fail-fast: true
    steps:
    - uses: actions/checkout@v2
    - name: Setup ${{ matrix.dotnet }} .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Run tests (Portability)
      # we want to run only once.
      if: startsWith(matrix.os, 'ubuntu-20')
      run: |
        dotnet build tests/DotNetLightning.Core.Tests -p:Portability=True --framework=${{ matrix.framework }}
        dotnet run --no-build --project tests/DotNetLightning.Core.Tests --framework=${{ matrix.framework }}

    - name: Clean to prepare for NSec build
      run: |
        dotnet clean
    - name: Run core tests
      run: |
        dotnet run --project tests/DotNetLightning.Core.Tests --framework=${{ matrix.framework }}
    - name: Run other tests
      run: |
        dotnet test --filter "FullyQualifiedName!~Macaroon" --framework=${{ matrix.framework }} # see https://github.com/joemphilips/DotNetLightning/issues/153

  build_with_fsharp_from_mono:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        DEBIAN_FRONTEND=noninteractive sudo apt install -y msbuild fsharp

        dotnet restore -p:Portability=True DotNetLightning.sln
        msbuild src/DotNetLightning.Core/DotNetLightning.Core.fsproj -p:Portability=True -p:TargetFramework=netstandard2.0

  style:
    needs: build_and_test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup .NET Core SDK 5.0.x
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'
      - name: fantomless
        run: |
          dotnet tool update --global fantomless-tool --version 4.7.997
          # path taken from https://stackoverflow.com/a/65367006/544947
          $HOME/.dotnet/tools/fantomless . --recurse
          git diff --exit-code

