name: Build DotNetLightning and deploy to NuGet
on: [pull_request]
jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
        dotnet: ['3.1.200']
      fail-fast: true
    steps:
    - uses: actions/checkout@v2
    - name: Setup ${{ matrix.dotnet }} .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Run tests (BouncyCastle)
      # we want to run only once.
      if: startsWith(matrix.os, 'ubuntu-18')
      run: |
        dotnet test tests/DotNetLightning.Core.Tests -p:BouncyCastle=True
    - name: Run Infrastructure tests on BouncyCastle
      # we want to run only once.
      if: startsWith(matrix.os, 'ubuntu-18')
      run: |
        dotnet test tests/DotNetLightning.Infrastructure.Tests -p:BouncyCastle=True

    - name: Clean to prepare for NSec build
      run: |
        dotnet clean
    - name: Run tests
      run: |
        dotnet test